import React, { useCallback, useMemo, useState } from 'react';
import {
  Alert,
  Box,
  Button,
  Card,
  CardContent,
  CardHeader,
  CircularProgress,
  InputAdornment,
  Link,
  Stack,
  TextField,
  Typography,
} from '@mui/material';
import { useRequest } from 'ahooks';
import { Link as RouterLink } from 'react-router-dom';

import {
  createEmailChallengeStandardJudgeEmailChallengePost,
  createStandardJudgeTaskStandardJudgePost,
  CreateStandardJudgeTaskResponse,
} from '../../api';

type FeedbackState = {
  type: 'success' | 'error';
  message: string;
} | null;

const useErrorMessage = () =>
  useCallback((error: unknown): string => {
    if (!error) return 'Something went wrong. Please try again.';
    if (typeof error === 'string') return error;
    if (error instanceof Error) return error.message;
    if (typeof (error as { message?: unknown })?.message === 'string') {
      return String((error as { message?: unknown }).message);
    }
    const response = (error as { response?: { data?: unknown } }).response;
    const responseData = response?.data as { detail?: unknown } | undefined;
    if (typeof responseData?.detail === 'string') {
      return responseData.detail;
    }
    return 'Something went wrong. Please try again.';
  }, []);

export const SubmitStandardJudge: React.FC = () => {
  const [model, setModel] = useState('');
  const [author, setAuthor] = useState('');
  const [email, setEmail] = useState('');
  const [challengeEmail, setChallengeEmail] = useState<string | null>(null);
  const [verificationCode, setVerificationCode] = useState('');
  const [file, setFile] = useState<File | null>(null);
  const [emailChallengeId, setEmailChallengeId] = useState<string | null>(null);
  const [emailFeedback, setEmailFeedback] = useState<FeedbackState>(null);
  const [submissionFeedback, setSubmissionFeedback] = useState<FeedbackState>(null);
  const [submissionResult, setSubmissionResult] = useState<CreateStandardJudgeTaskResponse | null>(null);
  const [fileError, setFileError] = useState<string | null>(null);

  const getErrorMessage = useErrorMessage();

  const { runAsync: requestEmailChallenge, loading: sendingChallenge } = useRequest(
    async (targetEmail: string) => {
      const response = await createEmailChallengeStandardJudgeEmailChallengePost<true>({
        body: {
          email: targetEmail,
        },
        throwOnError: true,
      });
      return response.data;
    },
    { manual: true },
  );

  const { runAsync: submitStandardJudgeTask, loading: submitting } = useRequest(
    async (payload: {
      authorValue: string;
      modelValue: string;
      verificationValue: string;
      challengeId: string;
      upload: File;
    }) => {
      const response = await createStandardJudgeTaskStandardJudgePost<true>({
        body: {
          model: payload.modelValue,
          author: payload.authorValue,
          email_challenge_id: payload.challengeId,
          email_verification_code: payload.verificationValue,
          file: payload.upload,
        },
        throwOnError: true,
      });
      return response.data;
    },
    { manual: true },
  );

  const selectedFileName = useMemo(() => file?.name ?? 'Choose JSON file', [file]);

  const statusLink = useMemo(() => {
    if (!submissionResult) return null;
    return `/projects/livecodebench-pro/task/${submissionResult.id}?secret=${encodeURIComponent(
      submissionResult.secret,
    )}`;
  }, [submissionResult]);

  const handleEmailChange = useCallback(
    (event: React.ChangeEvent<HTMLInputElement>) => {
      const nextEmail = event.target.value;
      setEmail(nextEmail);
      if (challengeEmail && nextEmail.trim() !== challengeEmail.trim()) {
        setEmailChallengeId(null);
        setChallengeEmail(null);
        setEmailFeedback(null);
      }
    },
    [challengeEmail],
  );

  const handleFileChange = useCallback((event: React.ChangeEvent<HTMLInputElement>) => {
    const selectedFile = event.target.files?.[0] ?? null;
    if (!selectedFile) {
      setFile(null);
      setFileError(null);
      return;
    }

    const fileName = selectedFile.name.toLowerCase();
    if (!fileName.endsWith('.json')) {
      setFile(null);
      setFileError('Upload the JSON file generated by the LiveCodeBench Pro benchmark toolkit.');
      event.target.value = '';
      return;
    }

    setFile(selectedFile);
    setFileError(null);
  }, []);

  const handleSendVerification = useCallback(async () => {
    setEmailFeedback(null);
    setSubmissionFeedback(null);
    setSubmissionResult(null);

    const trimmedEmail = email.trim();
    if (!trimmedEmail) {
      setEmailFeedback({ type: 'error', message: 'Please enter an email address.' });
      return;
    }

    try {
      const data = await requestEmailChallenge(trimmedEmail);
      const challengeId = data?.challenge_id;
      if (!challengeId) {
        setEmailFeedback({ type: 'error', message: 'Failed to retrieve a challenge id. Please retry.' });
        return;
      }

      setEmailChallengeId(challengeId);
      setChallengeEmail(trimmedEmail);
      setEmailFeedback({
        type: 'success',
        message: 'Verification code sent. Check your inbox and enter the code below.',
      });
    } catch (error) {
      setEmailFeedback({ type: 'error', message: getErrorMessage(error) });
    }
  }, [email, getErrorMessage, requestEmailChallenge]);

  const handleSubmit = useCallback(
    async (event: React.FormEvent<HTMLFormElement>) => {
      event.preventDefault();
      setSubmissionFeedback(null);
      setSubmissionResult(null);

      const trimmedModel = model.trim();
      const trimmedAuthor = author.trim();
      const trimmedVerification = verificationCode.trim();

      if (!trimmedModel || !trimmedAuthor || !trimmedVerification) {
        setSubmissionFeedback({ type: 'error', message: 'All fields are required before submitting.' });
        return;
      }
      if (!emailChallengeId) {
        setSubmissionFeedback({
          type: 'error',
          message: 'Please request and verify your email before submitting.',
        });
        return;
      }
      if (!file) {
        setSubmissionFeedback({
          type: 'error',
          message: 'Please attach the JSON export produced by the LiveCodeBench Pro benchmark toolkit.',
        });
        return;
      }
      if (fileError) {
        setSubmissionFeedback({ type: 'error', message: fileError });
        return;
      }

      try {
        const result = await submitStandardJudgeTask({
          authorValue: trimmedAuthor,
          modelValue: trimmedModel,
          verificationValue: trimmedVerification,
          challengeId: emailChallengeId,
          upload: file,
        });
        setSubmissionResult(result ?? null);
        setSubmissionFeedback({
          type: 'success',
          message: 'Submission received. Save the task id and secret shown below for tracking.',
        });
      } catch (error) {
        setSubmissionFeedback({ type: 'error', message: getErrorMessage(error) });
      }
    },
    [author, emailChallengeId, file, fileError, getErrorMessage, model, submitStandardJudgeTask, verificationCode],
  );

  return (
    <Card>
      <CardHeader
        title="Submit to the Standard Judge"
        subheader="Upload your model's run artifacts for evaluation on the LiveCodeBench Pro standard judge."
      />
      <CardContent>
        <Stack spacing={3}>
          <Typography variant="body2" sx={{ color: 'text.secondary' }}>
            Start by requesting a verification code. Once you receive it, provide your run details and upload the
            output bundle to queue a new evaluation.
          </Typography>

          <Box component="form" onSubmit={handleSubmit} noValidate>
            <Stack spacing={3}>
              <Stack spacing={2}>
                <TextField
                  label="Model"
                  value={model}
                  onChange={(event) => setModel(event.target.value)}
                  required
                  fullWidth
                />
                <TextField
                  label="Author"
                  value={author}
                  onChange={(event) => setAuthor(event.target.value)}
                  required
                  fullWidth
                />
              </Stack>

              <Stack spacing={1.5}>
                <TextField
                  label="Email"
                  type="email"
                  value={email}
                  onChange={handleEmailChange}
                  required
                  fullWidth
                  helperText={
                    emailChallengeId
                      ? `Verification code sent to ${challengeEmail ?? email}.`
                      : 'We will send a verification code to this address.'
                  }
                  InputProps={{
                    endAdornment: (
                      <InputAdornment position="end">
                        <Button
                          variant="outlined"
                          onClick={handleSendVerification}
                          disabled={sendingChallenge || !email.trim()}
                          size="small"
                          sx={{ ml: 1, whiteSpace: 'nowrap' }}
                        >
                          {sendingChallenge ? <CircularProgress size={16} /> : 'Send verification code'}
                        </Button>
                      </InputAdornment>
                    ),
                  }}
                />
                {emailFeedback && (
                  <Alert severity={emailFeedback.type}>{emailFeedback.message}</Alert>
                )}
              </Stack>

              <TextField
                label="Verification code"
                value={verificationCode}
                onChange={(event) => setVerificationCode(event.target.value)}
                required
                fullWidth
              />

              <Stack spacing={1.5}>
                <Stack direction={{ xs: 'column', sm: 'row' }} spacing={1.5} alignItems={{ sm: 'center' }}>
                  <Button
                    variant="outlined"
                    component="label"
                    sx={{ alignSelf: { xs: 'stretch', sm: 'flex-start' } }}
                  >
                    {selectedFileName}
                    <input
                      type="file"
                      hidden
                      accept=".json,application/json"
                      onChange={handleFileChange}
                    />
                  </Button>
                  {file && (
                    <Typography variant="body2" sx={{ color: 'text.secondary' }}>
                      {Math.round((file.size / 1024) * 10) / 10} KB
                    </Typography>
                  )}
                </Stack>
                {fileError && (
                  <Alert severity="error">{fileError}</Alert>
                )}
                <Typography variant="caption" sx={{ color: 'text.secondary' }}>
                  Upload the JSON results file produced by the benchmark toolkit at
                  {' '}
                  <Link href="https://github.com/GavinZhengOI/LiveCodeBench-Pro" target="_blank" rel="noopener">
                    github.com/GavinZhengOI/LiveCodeBench-Pro
                  </Link>
                  .
                </Typography>
              </Stack>

              {submissionFeedback && (
                <Alert severity={submissionFeedback.type}>{submissionFeedback.message}</Alert>
              )}

              {submissionResult && (
                <Alert severity="info">
                  <Stack spacing={1}>
                    <Stack spacing={0.5}>
                      <Typography variant="body2">
                        <strong>Task ID:</strong> {submissionResult.id}
                      </Typography>
                      <Typography variant="body2">
                        <strong>Secret:</strong> {submissionResult.secret}
                      </Typography>
                    </Stack>
                    {statusLink && (
                      <Button
                        variant="outlined"
                        component={RouterLink}
                        to={statusLink}
                        size="small"
                      >
                        View task status
                      </Button>
                    )}
                  </Stack>
                </Alert>
              )}

              <Button
                type="submit"
                variant="contained"
                disabled={submitting}
                sx={{ alignSelf: { xs: 'stretch', sm: 'flex-start' }, minWidth: { sm: 160 } }}
              >
                {submitting ? <CircularProgress size={18} sx={{ color: 'inherit' }} /> : 'Submit for evaluation'}
              </Button>
            </Stack>
          </Box>
        </Stack>
      </CardContent>
    </Card>
  );
};

export default SubmitStandardJudge;
