// This file is auto-generated by @hey-api/openapi-ts

import { type Options as ClientOptions, type TDataShape, type Client, formDataBodySerializer } from '@hey-api/client-axios';
import type { HealthHealthGetData, HandleUpdateWebhookIdUpdatePostData, HandleUpdateWebhookIdUpdatePostError, HandleFinalWebhookIdFinalPostData, HandleFinalWebhookIdFinalPostError, ListLlmLeaderboardLlmGetData, ListLlmLeaderboardLlmGetResponse, ListLlmByDifficultyLeaderboardLlmDifficultyGetData, ListLlmByDifficultyLeaderboardLlmDifficultyGetResponse, ListLlmByDifficultyLeaderboardLlmDifficultyGetError, GetLlmSubmissionsLeaderboardLlmSubmissionsGetData, GetLlmSubmissionsLeaderboardLlmSubmissionsGetResponse, GetLlmSubmissionsLeaderboardLlmSubmissionsGetError, GetSubmissionLeaderboardSubmissionSubmissionIdGetData, GetSubmissionLeaderboardSubmissionSubmissionIdGetResponse, GetSubmissionLeaderboardSubmissionSubmissionIdGetError, CreateEmailChallengeStandardJudgeEmailChallengePostData, CreateEmailChallengeStandardJudgeEmailChallengePostResponse, CreateEmailChallengeStandardJudgeEmailChallengePostError, CreateStandardJudgeTaskStandardJudgePostData, CreateStandardJudgeTaskStandardJudgePostResponse, CreateStandardJudgeTaskStandardJudgePostError, GetStandardJudgeTaskStandardJudgeTaskIdGetData, GetStandardJudgeTaskStandardJudgeTaskIdGetResponse, GetStandardJudgeTaskStandardJudgeTaskIdGetError, GetInputFileStandardJudgeCallbackInputFileGetData, GetOutputFileUploadUrlStandardJudgeCallbackOutputFileGetData, UpdateStatusStandardJudgeCallbackStatusPutData, UpdateStatusStandardJudgeCallbackStatusPutError, AppendLogStandardJudgeCallbackAppendLogPostData, AppendLogStandardJudgeCallbackAppendLogPostError } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Health
 */
export const healthHealthGet = <ThrowOnError extends boolean = false>(options?: Options<HealthHealthGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
        url: '/health',
        ...options
    });
};

/**
 * Handle Update
 */
export const handleUpdateWebhookIdUpdatePost = <ThrowOnError extends boolean = false>(options: Options<HandleUpdateWebhookIdUpdatePostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<unknown, HandleUpdateWebhookIdUpdatePostError, ThrowOnError>({
        url: '/{webhook_id}/update',
        ...options
    });
};

/**
 * Handle Final
 */
export const handleFinalWebhookIdFinalPost = <ThrowOnError extends boolean = false>(options: Options<HandleFinalWebhookIdFinalPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<unknown, HandleFinalWebhookIdFinalPostError, ThrowOnError>({
        url: '/{webhook_id}/final',
        ...options
    });
};

/**
 * List Llm
 * List all LLMs registered in the database.
 *
 * Returns a list of dictionaries, each containing the name, provider, status,
 * model_license, organization, and rating of an LLM. The rating is the
 * current rating of the LLM, and the ratingEvent is a list of dictionaries
 * containing the rating, time, contestId, and name of each rating change.
 */
export const listLlmLeaderboardLlmGet = <ThrowOnError extends boolean = false>(options?: Options<ListLlmLeaderboardLlmGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<ListLlmLeaderboardLlmGetResponse, unknown, ThrowOnError>({
        url: '/leaderboard/llm',
        ...options
    });
};

/**
 * List Llm By Difficulty
 */
export const listLlmByDifficultyLeaderboardLlmDifficultyGet = <ThrowOnError extends boolean = false>(options: Options<ListLlmByDifficultyLeaderboardLlmDifficultyGetData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<ListLlmByDifficultyLeaderboardLlmDifficultyGetResponse, ListLlmByDifficultyLeaderboardLlmDifficultyGetError, ThrowOnError>({
        url: '/leaderboard/llm/difficulty',
        ...options
    });
};

/**
 * Get Llm Submissions
 */
export const getLlmSubmissionsLeaderboardLlmSubmissionsGet = <ThrowOnError extends boolean = false>(options: Options<GetLlmSubmissionsLeaderboardLlmSubmissionsGetData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetLlmSubmissionsLeaderboardLlmSubmissionsGetResponse, GetLlmSubmissionsLeaderboardLlmSubmissionsGetError, ThrowOnError>({
        url: '/leaderboard/llm/submissions',
        ...options
    });
};

/**
 * Get Submission
 */
export const getSubmissionLeaderboardSubmissionSubmissionIdGet = <ThrowOnError extends boolean = false>(options: Options<GetSubmissionLeaderboardSubmissionSubmissionIdGetData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetSubmissionLeaderboardSubmissionSubmissionIdGetResponse, GetSubmissionLeaderboardSubmissionSubmissionIdGetError, ThrowOnError>({
        url: '/leaderboard/submission/{submission_id}',
        ...options
    });
};

/**
 * Create Email Challenge
 */
export const createEmailChallengeStandardJudgeEmailChallengePost = <ThrowOnError extends boolean = false>(options: Options<CreateEmailChallengeStandardJudgeEmailChallengePostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<CreateEmailChallengeStandardJudgeEmailChallengePostResponse, CreateEmailChallengeStandardJudgeEmailChallengePostError, ThrowOnError>({
        url: '/standard_judge/email_challenge',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Create Standard Judge Task
 */
export const createStandardJudgeTaskStandardJudgePost = <ThrowOnError extends boolean = false>(options: Options<CreateStandardJudgeTaskStandardJudgePostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<CreateStandardJudgeTaskStandardJudgePostResponse, CreateStandardJudgeTaskStandardJudgePostError, ThrowOnError>({
        ...formDataBodySerializer,
        url: '/standard_judge',
        ...options,
        headers: {
            'Content-Type': null,
            ...options?.headers
        }
    });
};

/**
 * Get Standard Judge Task
 */
export const getStandardJudgeTaskStandardJudgeTaskIdGet = <ThrowOnError extends boolean = false>(options: Options<GetStandardJudgeTaskStandardJudgeTaskIdGetData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetStandardJudgeTaskStandardJudgeTaskIdGetResponse, GetStandardJudgeTaskStandardJudgeTaskIdGetError, ThrowOnError>({
        url: '/standard_judge/{task_id}',
        ...options
    });
};

/**
 * Get Input File
 */
export const getInputFileStandardJudgeCallbackInputFileGet = <ThrowOnError extends boolean = false>(options?: Options<GetInputFileStandardJudgeCallbackInputFileGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/standard_judge/callback/input_file',
        ...options
    });
};

/**
 * Get Output File Upload Url
 */
export const getOutputFileUploadUrlStandardJudgeCallbackOutputFileGet = <ThrowOnError extends boolean = false>(options?: Options<GetOutputFileUploadUrlStandardJudgeCallbackOutputFileGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/standard_judge/callback/output_file',
        ...options
    });
};

/**
 * Update Status
 */
export const updateStatusStandardJudgeCallbackStatusPut = <ThrowOnError extends boolean = false>(options: Options<UpdateStatusStandardJudgeCallbackStatusPutData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).put<unknown, UpdateStatusStandardJudgeCallbackStatusPutError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/standard_judge/callback/status',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Append Log
 */
export const appendLogStandardJudgeCallbackAppendLogPost = <ThrowOnError extends boolean = false>(options: Options<AppendLogStandardJudgeCallbackAppendLogPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<unknown, AppendLogStandardJudgeCallbackAppendLogPostError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/standard_judge/callback/append_log',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};