// This file is auto-generated by @hey-api/openapi-ts

export type AppendLogRequest = {
    log: string;
};

export type BenchmarkMode = 'rating' | 'static' | 'live';

export type BodyCreateStandardJudgeTaskStandardJudgePost = {
    model: string;
    author: string;
    email_challenge_id: string;
    email_verification_code: string;
    file: Blob | File;
};

export type CreateEmailChallengeRequest = {
    email: string;
};

export type CreateEmailChallengeResponse = {
    challenge_id: string;
};

export type CreateStandardJudgeTaskResponse = {
    id: string;
    secret: string;
};

export type GetStandardJudgeTaskResponse = {
    model: string;
    author: string;
    input_file_url: string;
    status: 'pending' | 'instance_created' | 'running' | 'finished' | 'failed';
    created_at: number;
    instance_created_at?: number | null;
    running_at?: number | null;
    output_file_url?: string | null;
    finished_at?: number | null;
    failed_at?: number | null;
};

export type HttpValidationError = {
    detail?: Array<ValidationError>;
};

export type Llm = {
    name: string;
    provider: string;
    status: string;
    model_license?: string | null;
    organization?: string | null;
    rating?: number | string;
    display_name?: string | null;
    ratingEvent?: Array<RatingEvent>;
};

export type LlmByDifficulty = {
    name: string;
    provider: string;
    status: string;
    model_license?: string | null;
    organization?: string | null;
    rating?: number | string;
    display_name?: string | null;
    ratingEvent?: Array<RatingEvent>;
    validrate: number;
    passrate: number;
};

export type LlmContestProblemSubmission = {
    problem_index: string;
    problem_link: string;
    problem_name: string;
    problem_extra: string;
    verdict: 'accepted' | 'not_accepted' | 'unknown' | 'in_queue' | 'generation_failed' | 'in_batch' | 'compilation_error';
    status: string | null;
    submission_id: string | null;
};

export type LlmContestSubmissions = {
    contest_title: string;
    contest_link: string;
    contest_start_time: number;
    problems: Array<LlmContestProblemSubmission>;
};

export type LlmDifficulty = {
    llms: Array<LlmByDifficulty>;
    difficulty: ProblemDifficulty;
};

export type LlmSubmissions = {
    difficulty?: ProblemDifficulty;
    contests: Array<LlmContestSubmissions>;
};

export type ProblemDifficulty = 'easy' | 'medium' | 'hard' | 'all';

export type RatingEvent = {
    rating: number;
    time: number;
    contestId?: number | null;
    name?: string | null;
    calcRating?: number | null;
};

export type Submission = {
    problem_id: string;
    platform: 'codeforces';
    model_name: string;
    model_provider: string;
    verdict: string;
    code: string;
    status: string;
};

export type UpdateStatusRequest = {
    status: 'pending' | 'instance_created' | 'running' | 'finished' | 'failed';
};

export type ValidationError = {
    loc: Array<string | number>;
    msg: string;
    type: string;
};

export type HealthHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type HandleUpdateWebhookIdUpdatePostData = {
    body?: never;
    path: {
        webhook_id: string;
    };
    query?: never;
    url: '/{webhook_id}/update';
};

export type HandleUpdateWebhookIdUpdatePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type HandleUpdateWebhookIdUpdatePostError = HandleUpdateWebhookIdUpdatePostErrors[keyof HandleUpdateWebhookIdUpdatePostErrors];

export type HandleUpdateWebhookIdUpdatePostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type HandleFinalWebhookIdFinalPostData = {
    body?: never;
    path: {
        webhook_id: string;
    };
    query?: never;
    url: '/{webhook_id}/final';
};

export type HandleFinalWebhookIdFinalPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type HandleFinalWebhookIdFinalPostError = HandleFinalWebhookIdFinalPostErrors[keyof HandleFinalWebhookIdFinalPostErrors];

export type HandleFinalWebhookIdFinalPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListLlmLeaderboardLlmGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/leaderboard/llm';
};

export type ListLlmLeaderboardLlmGetResponses = {
    /**
     * Successful Response
     */
    200: Array<Llm>;
};

export type ListLlmLeaderboardLlmGetResponse = ListLlmLeaderboardLlmGetResponses[keyof ListLlmLeaderboardLlmGetResponses];

export type ListLlmByDifficultyLeaderboardLlmDifficultyGetData = {
    body?: never;
    path?: never;
    query: {
        difficulty: ProblemDifficulty;
        benchmark_mode?: BenchmarkMode;
        static_problemset?: string | null;
    };
    url: '/leaderboard/llm/difficulty';
};

export type ListLlmByDifficultyLeaderboardLlmDifficultyGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListLlmByDifficultyLeaderboardLlmDifficultyGetError = ListLlmByDifficultyLeaderboardLlmDifficultyGetErrors[keyof ListLlmByDifficultyLeaderboardLlmDifficultyGetErrors];

export type ListLlmByDifficultyLeaderboardLlmDifficultyGetResponses = {
    /**
     * Successful Response
     */
    200: LlmDifficulty;
};

export type ListLlmByDifficultyLeaderboardLlmDifficultyGetResponse = ListLlmByDifficultyLeaderboardLlmDifficultyGetResponses[keyof ListLlmByDifficultyLeaderboardLlmDifficultyGetResponses];

export type GetLlmSubmissionsLeaderboardLlmSubmissionsGetData = {
    body?: never;
    path?: never;
    query: {
        model_name: string;
        model_provider: string;
        difficulty: ProblemDifficulty;
        benchmark_mode?: BenchmarkMode;
        problemset_name?: string | null;
    };
    url: '/leaderboard/llm/submissions';
};

export type GetLlmSubmissionsLeaderboardLlmSubmissionsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetLlmSubmissionsLeaderboardLlmSubmissionsGetError = GetLlmSubmissionsLeaderboardLlmSubmissionsGetErrors[keyof GetLlmSubmissionsLeaderboardLlmSubmissionsGetErrors];

export type GetLlmSubmissionsLeaderboardLlmSubmissionsGetResponses = {
    /**
     * Successful Response
     */
    200: LlmSubmissions;
};

export type GetLlmSubmissionsLeaderboardLlmSubmissionsGetResponse = GetLlmSubmissionsLeaderboardLlmSubmissionsGetResponses[keyof GetLlmSubmissionsLeaderboardLlmSubmissionsGetResponses];

export type GetSubmissionLeaderboardSubmissionSubmissionIdGetData = {
    body?: never;
    path: {
        submission_id: string;
    };
    query?: never;
    url: '/leaderboard/submission/{submission_id}';
};

export type GetSubmissionLeaderboardSubmissionSubmissionIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetSubmissionLeaderboardSubmissionSubmissionIdGetError = GetSubmissionLeaderboardSubmissionSubmissionIdGetErrors[keyof GetSubmissionLeaderboardSubmissionSubmissionIdGetErrors];

export type GetSubmissionLeaderboardSubmissionSubmissionIdGetResponses = {
    /**
     * Successful Response
     */
    200: Submission | null;
};

export type GetSubmissionLeaderboardSubmissionSubmissionIdGetResponse = GetSubmissionLeaderboardSubmissionSubmissionIdGetResponses[keyof GetSubmissionLeaderboardSubmissionSubmissionIdGetResponses];

export type CreateEmailChallengeStandardJudgeEmailChallengePostData = {
    body: CreateEmailChallengeRequest;
    path?: never;
    query?: never;
    url: '/standard_judge/email_challenge';
};

export type CreateEmailChallengeStandardJudgeEmailChallengePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateEmailChallengeStandardJudgeEmailChallengePostError = CreateEmailChallengeStandardJudgeEmailChallengePostErrors[keyof CreateEmailChallengeStandardJudgeEmailChallengePostErrors];

export type CreateEmailChallengeStandardJudgeEmailChallengePostResponses = {
    /**
     * Successful Response
     */
    200: CreateEmailChallengeResponse;
};

export type CreateEmailChallengeStandardJudgeEmailChallengePostResponse = CreateEmailChallengeStandardJudgeEmailChallengePostResponses[keyof CreateEmailChallengeStandardJudgeEmailChallengePostResponses];

export type CreateStandardJudgeTaskStandardJudgePostData = {
    body: BodyCreateStandardJudgeTaskStandardJudgePost;
    path?: never;
    query?: never;
    url: '/standard_judge';
};

export type CreateStandardJudgeTaskStandardJudgePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateStandardJudgeTaskStandardJudgePostError = CreateStandardJudgeTaskStandardJudgePostErrors[keyof CreateStandardJudgeTaskStandardJudgePostErrors];

export type CreateStandardJudgeTaskStandardJudgePostResponses = {
    /**
     * Successful Response
     */
    200: CreateStandardJudgeTaskResponse;
};

export type CreateStandardJudgeTaskStandardJudgePostResponse = CreateStandardJudgeTaskStandardJudgePostResponses[keyof CreateStandardJudgeTaskStandardJudgePostResponses];

export type GetStandardJudgeTaskStandardJudgeTaskIdGetData = {
    body?: never;
    path: {
        task_id: string;
    };
    query: {
        secret: string;
    };
    url: '/standard_judge/{task_id}';
};

export type GetStandardJudgeTaskStandardJudgeTaskIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetStandardJudgeTaskStandardJudgeTaskIdGetError = GetStandardJudgeTaskStandardJudgeTaskIdGetErrors[keyof GetStandardJudgeTaskStandardJudgeTaskIdGetErrors];

export type GetStandardJudgeTaskStandardJudgeTaskIdGetResponses = {
    /**
     * Successful Response
     */
    200: GetStandardJudgeTaskResponse;
};

export type GetStandardJudgeTaskStandardJudgeTaskIdGetResponse = GetStandardJudgeTaskStandardJudgeTaskIdGetResponses[keyof GetStandardJudgeTaskStandardJudgeTaskIdGetResponses];

export type GetInputFileStandardJudgeCallbackInputFileGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/standard_judge/callback/input_file';
};

export type GetInputFileStandardJudgeCallbackInputFileGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetOutputFileUploadUrlStandardJudgeCallbackOutputFileGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/standard_judge/callback/output_file';
};

export type GetOutputFileUploadUrlStandardJudgeCallbackOutputFileGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UpdateStatusStandardJudgeCallbackStatusPutData = {
    body: UpdateStatusRequest;
    path?: never;
    query?: never;
    url: '/standard_judge/callback/status';
};

export type UpdateStatusStandardJudgeCallbackStatusPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateStatusStandardJudgeCallbackStatusPutError = UpdateStatusStandardJudgeCallbackStatusPutErrors[keyof UpdateStatusStandardJudgeCallbackStatusPutErrors];

export type UpdateStatusStandardJudgeCallbackStatusPutResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AppendLogStandardJudgeCallbackAppendLogPostData = {
    body: AppendLogRequest;
    path?: never;
    query?: never;
    url: '/standard_judge/callback/append_log';
};

export type AppendLogStandardJudgeCallbackAppendLogPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AppendLogStandardJudgeCallbackAppendLogPostError = AppendLogStandardJudgeCallbackAppendLogPostErrors[keyof AppendLogStandardJudgeCallbackAppendLogPostErrors];

export type AppendLogStandardJudgeCallbackAppendLogPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ClientOptions = {
    baseURL: 'https://webhook.cp-bench.orzzh.com' | (string & {});
};